# Generated by Django 3.0 on 2020-08-05 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='color',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='name',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='ripe',
        ),
        migrations.AddField(
            model_name='trip',
            name='tripEnd',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='tripStart',
            field=models.DateField(null=True),
        ),
    ]
