# Generated by Django 3.0 on 2020-08-09 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200805_1638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='tripEnd',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='tripStart',
            new_name='launchDate',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='location',
            new_name='longitude',
        ),
    ]
