# Generated by Django 3.0 on 2020-08-10 01:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200809_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='latitude',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trip',
            name='longitude',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
    ]
